// src/components/Layout/Header.tsx
import ThemeToggler from './ThemeToggler'
import clsx from 'clsx'
import { useState, Fragment } from 'react'
import useWindowEventListener from '~/hooks/useWindowEventListener'
import { Dialog, Transition } from '@headlessui/react'
import { XMarkIcon, Bars3BottomLeftIcon } from '@heroicons/react/24/outline'

const links: { name: string; href: string }[] = [
    {
        name: 'Home',
        href: '/',
    },
    {
        name: 'About me',
        href: '/about',
    },
    {
        name: 'Projects',
        href: '/projects',
    },
    {
        name: 'Blog',
        href: '/blog',
    },
    {
        name: 'Get in touch',
        href: '#contact',
    },
]

function MobileMenu({
    open,
    onClose,
    pathname,
}: {
    open: boolean
    onClose: () => void
    pathname: string
}) {
    return (
        <Transition.Root show={open} as={Fragment}>
            <Dialog
                as="div"
                className="relative z-50 sm:hidden"
                onClose={onClose}
            >
                <Transition.Child
                    as={Fragment}
                    enter="ease-in-out duration-500"
                    enterFrom="opacity-0"
                    enterTo="opacity-100"
                    leave="ease-in-out duration-500"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                >
                    <div className="fixed inset-0 bg-neutralDark-3 bg-opacity-75 transition-opacity" />
                </Transition.Child>

                <div className="fixed inset-0 overflow-hidden">
                    <div className="absolute inset-0 overflow-hidden">
                        <div className="pointer-events-none fixed inset-x-0 bottom-0 flex max-h-full pt-10">
                            <Transition.Child
                                as={Fragment}
                                enter="transform transition ease-in-out duration-500 sm:duration-700"
                                enterFrom="translate-y-full"
                                enterTo="translate-y-0"
                                leave="transform transition ease-in-out duration-500 sm:duration-700"
                                leaveFrom="translate-y-0"
                                leaveTo="translate-y-full"
                            >
                                <Dialog.Panel className="pointer-events-auto mx-auto w-screen max-w-md">
                                    <div className="flex h-full flex-col overflow-y-auto rounded-t-xl bg-neutral-4 py-6 shadow-xl">
                                        <div className="px-4 sm:px-6">
                                            <div className="flex items-start justify-between">
                                                <Dialog.Title className="ml-4 text-xl font-semibold">
                                                    Menu
                                                </Dialog.Title>
                                                <div className="ml-3 flex h-7 items-center">
                                                    <button
                                                        className="p-2 transition-colors hover:bg-neutral-4 focus:outline-none focus:ring-[3px] focus:ring-primary-7"
                                                        onClick={() =>
                                                            onClose()
                                                        }
                                                    >
                                                        <span className="sr-only">
                                                            Close menu
                                                        </span>
                                                        <XMarkIcon
                                                            className="h-6 w-6"
                                                            aria-hidden="true"
                                                        />
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="relative mt-6 flex-1 px-4 sm:px-6">
                                            <div className="flex flex-col items-center space-y-2">
                                                {links.map(({ name, href }) => (
                                                    <a
                                                        key={href}
                                                        className={clsx(
                                                            'w-full px-4 py-2 transition-colors hover:bg-neutral-4 focus:outline-none focus:ring-[3px] focus:ring-primary-7',
                                                            pathname === href
                                                                ? 'font-bold'
                                                                : 'font-medium'
                                                        )}
                                                        href={href}
                                                    >
                                                        {name}
                                                    </a>
                                                ))}
                                            </div>
                                        </div>
                                    </div>
                                </Dialog.Panel>
                            </Transition.Child>
                        </div>
                    </div>
                </div>
            </Dialog>
        </Transition.Root>
    )
}

export default function Header({ pathname }: { pathname: string }) {
    const [isTop, setIsTop] = useState(true)
    const [open, setOpen] = useState(false)
    useWindowEventListener('scroll', () => setIsTop(window.scrollY < 100), {
        passive: true,
    })
    return (
        <header
            className={clsx(
                'sticky top-0 z-40 border-b bg-neutral-2 transition-[border,_box-shadow] dark:bg-neutralDark-3',
                isTop ? 'border-transparent' : 'border-neutral-5 shadow-sm'
            )}
        >
            <nav className="custom-container relative flex items-center justify-center p-4 sm:justify-between">
                <button
                    className="absolute left-4 p-2 transition-colors hover:bg-neutral-4 focus:outline-none focus:ring-[3px] focus:ring-primary-7 sm:hidden"
                    onClick={() => setOpen(true)}
                >
                    <span className="sr-only">Open menu</span>
                    <Bars3BottomLeftIcon
                        className="h-6 w-6"
                        aria-hidden="true"
                    />
                </button>
                <a
                    href="/"
                    className="p-1 transition-colors hover:bg-neutral-4 focus:outline-none focus:ring-[3px] focus:ring-primary-7"
                >
                    <svg
                        className="h-8 w-8"
                        viewBox="0 0 48 48"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            fillRule="evenodd"
                            clipRule="evenodd"
                            d="M14.0656 19.9999L16.2822 11.7273C17.3175 7.8636 21.0574 4.72459 24.1483 5.55281L20.2037 20.2744C23.3482 21.0541 26 23.3944 26 25.9999H18.6696L15.8661 36.4624C14.8308 40.3262 11.091 43.4652 8.00002 42.6369L12.4925 25.8707C9.05343 25.2863 6 22.7958 6 19.9999H14.0656Z"
                            fill="currentColor"
                        ></path>
                        <path
                            d="M30.0781 40.5293C29.1418 41.2807 28.1646 41.6974 27.27 41.7612L35.2482 11.9862C35.7088 10.267 36.7795 8.69644 38.0703 7.66062C39.0065 6.90929 39.9838 6.49257 40.8784 6.42879L32.9002 36.2037C32.4395 37.9229 31.3689 39.4935 30.0781 40.5293Z"
                            fill="currentColor"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinejoin="round"
                        ></path>
                    </svg>
                </a>
                <div className="flex items-center space-x-4">
                    <div className="hidden items-center sm:flex">
                        {links.map(({ name, href }) => (
                            <a
                                key={href}
                                className={clsx(
                                    'px-4 py-2 transition-colors hover:bg-neutral-4 focus:outline-none focus:ring-[3px] focus:ring-primary-7',
                                    pathname === href
                                        ? 'font-bold'
                                        : 'font-medium'
                                )}
                                href={href}
                            >
                                {name}
                            </a>
                        ))}
                    </div>
                    <div className="absolute right-4 sm:static">
                        <ThemeToggler />
                    </div>
                </div>
            </nav>
            <MobileMenu
                open={open}
                onClose={() => setOpen(false)}
                pathname={pathname}
            />
        </header>
    )
}

// components/Header.vue
<template>
  <div class="sticky top-0 z-40">
    <Popover class="relative" v-slot="{ close }">
      <div
        class="h-16 border-b border-gray-800 bg-gray-900/90 backdrop-blur-md"
      >
        <Container class="flex h-full items-center justify-between py-4">
          <ProfilePicture />
          <div class="flex items-center space-x-4 sm:space-x-6">
            <div class="hidden items-center space-x-6 sm:flex">
              <component
                :is="link.external ? 'a' : 'nuxt-link'"
                v-for="link in links"
                :to="link.url"
                :href="link.url"
                :target="link.external ? '_blank' : undefined"
                class="relative text-white after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-full after:origin-bottom-right after:scale-x-0 after:rounded-full after:bg-gradient-to-tr after:from-primary-600 after:to-secondary-400 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                :class="{
                  'bg-gradient-to-tr from-primary-600 to-secondary-400 bg-clip-text font-semibold text-transparent':
                    link.url === '/'
                      ? $route.path === '/'
                      : $route.path.startsWith(link.url),
                }"
              >
                {{ link.name }}
              </component>
            </div>
            <a
              href="#contact"
              class="rounded-full bg-white px-6 py-2 font-medium text-gray-900 duration-300 hover:scale-95 focus:outline-none"
            >
              Contact
            </a>
            <PopoverButton
              class="inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-200 transition-all hover:bg-gray-700 focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 focus:ring-offset-gray-900 sm:hidden"
            >
              <span class="sr-only">Open menu</span>
              <MenuIcon class="h-6 w-6" aria-hidden="true" />
            </PopoverButton>
          </div>
        </Container>
      </div>
      <transition
        enter-active-class="duration-200 ease-out"
        enter-from-class="scale-95 opacity-0"
        enter-to-class="scale-100 opacity-100"
        leave-active-class="duration-100 ease-in"
        leave-from-class="scale-100 opacity-100"
        leave-to-class="scale-95 opacity-0"
      >
        <PopoverPanel
          focus
          class="fixed inset-0 z-50 flex origin-center transform items-center justify-center bg-gray-900 p-4 transition sm:hidden"
        >
          <PopoverButton
            class="absolute top-4 right-4 inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-200 transition-all hover:bg-gray-700 focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 focus:ring-offset-gray-900 sm:hidden"
          >
            <span class="sr-only">Open menu</span>
            <XIcon class="h-6 w-6" aria-hidden="true" />
          </PopoverButton>
          <div
            class="flex flex-col items-center justify-center space-y-6 text-xl"
          >
            <nuxt-link
              v-for="link in links"
              :to="link.url"
              @click.native="() => close()"
              class="relative text-white after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-full after:origin-bottom-right after:scale-x-0 after:rounded-full after:bg-gradient-to-tr after:from-primary-600 after:to-secondary-400 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
              active-class="font-semibold text-transparent bg-clip-text bg-gradient-to-tr from-primary-600 to-secondary-400"
            >
              {{ link.name }}
            </nuxt-link>
          </div>
        </PopoverPanel>
      </transition>
    </Popover>
  </div>
</template>

<script setup lang="ts">
import { PopoverButton, PopoverPanel, Popover } from "@headlessui/vue";
import { MenuIcon, XIcon } from "@heroicons/vue/outline";
import { Link } from "~/types";

const links: Link[] = [
  { name: "Home", url: "/" },
  { name: "About me", url: "/about" },
  { name: "Projects", url: "/projects" },
  { name: "Blog", url: "/blog" },
  {
    name: "Github",
    url: "https://github.com/florian-lefebvre",
    external: true,
  },
];
</script>
