// components/Projects/Card.vue
<template>
  <NuxtLink
    :to="`/projects/${project.locales[$i18n.locale].slug}`"
    class="relative flex h-full flex-col overflow-visible rounded-xl bg-gray-800 text-white shadow-lg transition-all hover:scale-95 hover:shadow"
  >
    <div class="absolute top-3 left-3">
      <div class="bg-gradient rounded-full px-3 py-1 text-sm text-white">
        {{ project.locales[$i18n.locale].type }}
      </div>
    </div>
    <div class="p-1">
      <img
        :src="project.global.imageUrl"
        class="h-48 w-full overflow-hidden rounded-lg object-cover object-center sm:h-64 md:h-48"
        :alt="`${project.locales[$i18n.locale].name} thumbnail`"
        loading="lazy"
      />
    </div>
    <div class="flex h-full flex-col p-4">
      <div class="mb-2 text-xl font-semibold text-white">
        {{ project.locales[$i18n.locale].name }}
      </div>
      <div class="mb-4 text-gray-300 line-clamp-3">
        {{ project.locales[$i18n.locale].description }}
      </div>
      <div class="mt-auto text-sm text-gray-400" v-if="detailed">
        {{ project.global.technologies.join(", ") }}
      </div>
    </div>
  </NuxtLink>
</template>

<script lang="ts" setup>
import { Project } from "~/types";
defineProps<{ project: Project; detailed?: boolean }>();
</script>

// src/components/Blog/Card.tsx
import i18next from 'i18next'
import { LazyLoadImage } from 'react-lazy-load-image-component'

type Props = {
    title: string
    description: string
    slug: string
    img: string
    alt: string
    category: string
    publishedTime: string
    localizedRootUrl: string
}

export default function ArticleCard({
    title,
    description,
    slug,
    img,
    alt,
    category,
    publishedTime,
    localizedRootUrl,
}: Props) {
    return (
        <a
            href={`${localizedRootUrl}${slug}`}
            className="group flex flex-col gap-4 focus:outline-none focus:ring-3 focus:ring-primary-7"
        >
            <div className="overflow-hidden">
                <LazyLoadImage
                    src={img}
                    alt={alt}
                    className="h-72 w-full object-cover transition-transform group-hover:scale-105"
                    loading="lazy"
                    placeholder={<div className="h-72 bg-primary-5"></div>}
                />
            </div>
            <p className="text-sm text-neutral-11">
                {category} ·{' '}
                {new Date(publishedTime).toLocaleDateString(i18next.language, {
                    dateStyle: 'medium',
                })}
            </p>
            <h3 className="text-xl font-semibold sm:text-2xl md:text-3xl">
                {title}
            </h3>
            <p className="text-base font-medium text-neutral-11">
                {description}
            </p>
        </a>
    )
}
