// src/components/Projects/Card.tsx
import { Icon } from '@iconify/react'
import clsx from 'clsx'
import { LazyLoadImage } from 'react-lazy-load-image-component'

type Props = {
    title: string
    desc: string
    slug: string
    img: string
    alt: string
    variant: 'small' | 'medium'
}

export default function ProjectCard({
    title,
    desc,
    slug,
    img,
    alt,
    variant,
}: Props) {
    function getClass(
        className: string,
        map: Record<Props['variant'], string>
    ) {
        return clsx(className, map[variant])
    }
    const wrapperClass = getClass(
        'flex flex-col gap-4 group focus:outline-none focus:ring-[3px] focus:ring-primary-6',
        {
            small: '',
            medium: '',
        }
    )
    const imgClass = getClass(
        'object-cover group-hover:scale-105 transition-transform w-full',
        { small: 'h-72 md:h-48', medium: 'h-72' }
    )
    const titleClass = getClass('font-semibold text-xl sm:text-2xl', {
        small: '',
        medium: 'md:text-3xl',
    })
    const descClass = getClass(
        'font-medium text-neutral-11 text-xs sm:text-base',
        {
            small: '',
            medium: '',
        }
    )
    const linkClass = getClass(
        'inline-flex mr-auto items-center space-x-2 font-semibold pb-1 border-b-2 border-transparent group-hover:border-current transition-colors text-sm sm:text-base',
        {
            small: '',
            medium: '',
        }
    )
    return (
        <a href={`/projects/${slug}`} className={wrapperClass}>
            <div className="overflow-hidden">
                <LazyLoadImage
                    src={img}
                    alt={alt}
                    className={imgClass}
                    loading="lazy"
                    placeholder={<span className="bg-primary-5"></span>}
                />
            </div>
            <h3 className={titleClass}>{title}</h3>
            <p className={descClass}>{desc}</p>
            <div className={linkClass}>
                <span>View project</span>
                <Icon
                    icon="heroicons:chevron-right-20-solid"
                    className="h-4 w-4"
                />
            </div>
        </a>
    )
}

// components/Projects/Card.vue
<template>
  <NuxtLink
    :to="`/projects/${project.locales[$i18n.locale].slug}`"
    class="group relative flex h-full flex-col overflow-hidden rounded-xl bg-gray-800 text-white shadow-lg transition-all hover:scale-95 hover:shadow"
  >
    <div
      class="bg-gradient absolute inset-0 z-[15] flex translate-y-full items-center justify-center rounded-xl !bg-opacity-40 transition-all group-hover:translate-y-0"
    >
      <div class="flex flex-col items-center">
        <EyeIcon class="h-16 w-16 text-white/80" />
        <div class="text-2xl font-semibold">
          {{ $t("global.projects.view") }}
        </div>
      </div>
    </div>
    <div class="absolute top-3 left-3 z-[14]">
      <div class="bg-gradient rounded-full px-3 py-1 text-sm text-white">
        {{ project.locales[$i18n.locale].type }}
      </div>
    </div>
    <div class="p-1">
      <img
        :src="project.global.imageUrl"
        class="h-48 w-full overflow-hidden rounded-lg object-cover object-center sm:h-64 md:h-48"
        :alt="`${project.locales[$i18n.locale].name} thumbnail`"
        loading="lazy"
      />
    </div>
    <div class="flex h-full flex-col p-4">
      <div class="mb-2 text-xl font-semibold text-white">
        {{ project.locales[$i18n.locale].name }}
      </div>
      <div class="mb-4 text-gray-300 line-clamp-3">
        {{ project.locales[$i18n.locale].description }}
      </div>
      <div class="mt-auto text-sm text-gray-400" v-if="detailed">
        {{ project.global.technologies.join(", ") }}
      </div>
    </div>
  </NuxtLink>
</template>

<script lang="ts" setup>
import { Project } from "~/types";
import { EyeIcon } from "@heroicons/vue/solid";
defineProps<{ project: Project; detailed?: boolean }>();
</script>
